#docker compose -f docker-compose.test.yml up --build --abort-on-container-exit

services:
  backend_test:
    build: .
    container_name: backend_test
    command: pytest -v /tests
    volumes:
      - ./app:/app
      - ./tests:/tests
    working_dir: /app
    environment:
      - APP_ENV=test
      - PYTHONPATH=/
