services:
  backend_v2_input_annotation_test:
    container_name: backend_v2_input_annotation_test
    build: .       #./backend/application_name
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    ports:
      - "821:8000" # "82:8000"
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      - APP_ENV=test
      - PYTHONPATH=/
      - DATABASE_URL=mysql+pymysql://test_user:test_user_password@db_test:3306/test_db
    depends_on:
      db_test:
        condition: service_healthy

  db_test:
    image: mysql:8.0
    container_name: mysql_db_v2_input_annotation_test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test_root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_user_password
      TZ: Asia/Tokyo
    ports:
      - "33061:3306"    # 3306:3306
    volumes:
      - db_data:/var/lib/mysql_test
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptest_root_password"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  db_data:
